# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore all logback updates because it is aligned to Spring Boot 3.2.x
      - dependency-name: "ch.qos.logback:logback-classic"
      # Ignore all AssertJ updates because it is aligned to Spring Boot 3.2.x
      - dependency-name: "org.assertj:assertj-core"
      # Ignore all JUnit updates because it is aligned to Spring Boot 3.2.x
      - dependency-name: "org.junit:junit-bom"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
