name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile, test and package library
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Compile, test, and package library
        run: ./mvnw --batch-mode --errors --no-transfer-progress --show-version verify
